name: Build ranking.json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    paths:
      - "chars.txt"
      - "scripts/**"
      - ".github/workflows/build-ranking.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright Chromium
        run: |
          npm init -y
          npm i playwright
          npx playwright install --with-deps chromium

      - name: Build ranking.json
        run: node scripts/buildRanking.mjs

      - name: Commit ranking.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/ranking.json
          git commit -m "Update ranking.json" || echo "No changes"
          git push
